version: '3.8'

services:
  wazebot:
    build: .
    container_name: wazebot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./logs:/app/logs
    networks:
      - wazebot-network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SYS_ADMIN  # Required for Chrome sandbox
    shm_size: 2gb  # Increase shared memory for Chrome

networks:
  wazebot-network:
    driver: bridge 